"""
archive_utils.py
================
Shared, filesystem-only utilities for the local web archiver.

Both the crawler (writer) and the Flask server (reader) import this module
so that folder naming, resource classification, and JSON schemas never
drift apart between the two. There is no database anywhere in this
project -- every fact about a snapshot lives on disk as either a directory
name, a file name, or a small JSON sidecar file.

Directory convention
---------------------
full-archive/
    <capture_date>/
        <site_name>/
            index.html
            meta.json
            resource_map.json
            resources/
                css/
                js/
                img/
                fonts/
                other/

<capture_date>  -- calendar date "YYYY-MM-DD"
<site_name>     -- sanitized hostname, e.g. "example.com"

Each site appears at most once per date. The exact capture time is
recorded in meta.json for reference but does not appear in the path.

Note: date is the outer folder. This makes "list available dates" and
"list sites on a given date" both cheap directory scans, which is what
the frontend calendar view needs most often.
"""

from __future__ import annotations

import hashlib
import json
import mimetypes
import os
import re
import time
from pathlib import Path
from typing import Optional
from urllib.parse import urlparse

# ---------------------------------------------------------------------------
# Root location
# ---------------------------------------------------------------------------

# All snapshots live under this directory. Resolved relative to this file so
# the crawler and the server agree on the same folder regardless of the
# working directory they're launched from.
PROJECT_ROOT = Path(__file__).resolve().parent
ARCHIVE_ROOT = PROJECT_ROOT / "full-archive"

# Resource categories and the subfolder each one is stored under.
RESOURCE_CATEGORIES = ("css", "js", "img", "fonts", "other")

# Extension -> category, used as a fast first pass before falling back to
# content-type sniffing.
_EXT_TO_CATEGORY = {
    ".css": "css",
    ".js": "js", ".mjs": "js",
    ".png": "img", ".jpg": "img", ".jpeg": "img", ".gif": "img",
    ".webp": "img", ".bmp": "img", ".ico": "img", ".avif": "img",
    ".svg": "img",
    ".woff": "fonts", ".woff2": "fonts", ".ttf": "fonts",
    ".otf": "fonts", ".eot": "fonts",
}

_CONTENT_TYPE_TO_CATEGORY = {
    "text/css": "css",
    "application/javascript": "js",
    "text/javascript": "js",
    "application/x-javascript": "js",
    "image/": "img",          # prefix match, handled specially below
    "font/": "fonts",         # prefix match
    "application/font-woff": "fonts",
    "application/vnd.ms-fontobject": "fonts",
    "application/x-font-ttf": "fonts",
}


# ---------------------------------------------------------------------------
# Naming helpers
# ---------------------------------------------------------------------------

def sanitize_site_name(url: str) -> str:
    """
    Turn a URL into a filesystem-safe, unique folder name based on both
    hostname and path so that different pages from the same domain each
    get their own folder.

    https://example.com/                       ->  "example.com"
    https://example.com/term-insurance-plans   ->  "example.com_term-insurance-plans"
    https://sub.example.co.uk:8080/a/b/c       ->  "sub.example.co.uk_8080_a_b_c"
    """
    parsed = urlparse(url)
    host = parsed.hostname or parsed.path or "unknown-site"
    host = host.lower()
    if host.startswith("www."):
        host = host[4:]
    if parsed.port:
        host = f"{host}_{parsed.port}"

    path = parsed.path.rstrip("/")
    if path:
        safe_path = path.lstrip("/").replace("/", "_")
        safe_path = re.sub(r"[^a-z0-9.\-_]", "_", safe_path)
        name = f"{host}_{safe_path}" if safe_path else host
    else:
        name = host

    name = re.sub(r"[^a-z0-9.\-_]", "_", name)
    return name or "unknown-site"


def make_capture_timestamp() -> str:
    """Return a sortable, filesystem-safe timestamp, e.g. '2026-07-29_14-32-05'."""
    return time.strftime("%Y-%m-%d_%H-%M-%S")


def make_capture_date() -> str:
    """Return today's calendar date, e.g. '2026-07-29'."""
    return time.strftime("%Y-%m-%d")


def _safe_path_component(value: str) -> str:
    """
    Reject anything that looks like a path-traversal attempt.
    Used whenever a site name or timestamp arrives from an HTTP request
    (i.e. from the Flask server) rather than being generated by our own code.
    """
    if not value or value in (".", "..") or "/" in value or "\\" in value:
        raise ValueError(f"Unsafe path component: {value!r}")
    return value


# ---------------------------------------------------------------------------
# Snapshot directory helpers
# ---------------------------------------------------------------------------

def get_snapshot_dir(site_name: str, capture_date: str, create: bool = False) -> Path:
    """
    Return the on-disk path for a given (capture_date, site) snapshot.

    If create=True, also creates the snapshot dir and its resources/<category>
    subfolders (used by the crawler before it starts writing files).
    """
    site_name = _safe_path_component(site_name)
    capture_date = _safe_path_component(capture_date)
    snapshot_dir = ARCHIVE_ROOT / capture_date / site_name

    if create:
        for category in RESOURCE_CATEGORIES:
            (snapshot_dir / "resources" / category).mkdir(parents=True, exist_ok=True)

    return snapshot_dir


def list_sites() -> list[str]:
    """Return every archived site name, sorted alphabetically.

    Since the layout is date-first, we scan all date directories and
    collect the unique site subdirectory names inside them.
    """
    if not ARCHIVE_ROOT.exists():
        return []
    sites: set[str] = set()
    for date_dir in ARCHIVE_ROOT.iterdir():
        if not date_dir.is_dir() or date_dir.name.startswith("."):
            continue
        for site_dir in date_dir.iterdir():
            if site_dir.is_dir() and (site_dir / "index.html").exists():
                sites.add(site_dir.name)
    return sorted(sites)


def list_snapshots(site_name: str) -> list[str]:
    """
    Return every capture date available for a site, sorted oldest first.

    Iterates all date directories under the archive root and includes
    those that contain a subdirectory for this site with an index.html.
    """
    site_name = _safe_path_component(site_name)
    if not ARCHIVE_ROOT.exists():
        return []
    dates: list[str] = []
    for date_dir in ARCHIVE_ROOT.iterdir():
        if not date_dir.is_dir() or date_dir.name.startswith("."):
            continue
        if (date_dir / site_name / "index.html").exists():
            dates.append(date_dir.name)
    return sorted(dates)


def resolve_snapshot_path(site_name: str, capture_date: str) -> Optional[Path]:
    """
    Safely resolve (site, date) to a real, existing directory on disk.
    Returns None if the snapshot doesn't exist or the inputs are unsafe.
    This is the only function the Flask server should use to turn request
    parameters into a filesystem path -- it never trusts the caller.
    """
    try:
        snapshot_dir = get_snapshot_dir(site_name, capture_date, create=False)
    except ValueError:
        return None

    try:
        resolved = snapshot_dir.resolve()
        resolved.relative_to(ARCHIVE_ROOT.resolve())
    except (ValueError, OSError):
        return None

    if not resolved.exists() or not (resolved / "index.html").exists():
        return None

    return resolved


# ---------------------------------------------------------------------------
# Resource classification + naming
# ---------------------------------------------------------------------------

def classify_resource(url: str, content_type: str = "") -> str:
    """
    Decide which resources/<category>/ folder a downloaded resource belongs in.
    Checked in order: URL extension, then content-type, then 'other'.
    """
    ext = os.path.splitext(urlparse(url).path)[1].lower()
    if ext in _EXT_TO_CATEGORY:
        return _EXT_TO_CATEGORY[ext]

    content_type = (content_type or "").split(";")[0].strip().lower()
    if content_type in _CONTENT_TYPE_TO_CATEGORY:
        return _CONTENT_TYPE_TO_CATEGORY[content_type]
    if content_type.startswith("image/"):
        return "img"
    if content_type.startswith("font/"):
        return "fonts"

    return "other"


def local_filename_for(url: str, content_type: str = "") -> str:
    """
    Deterministically derive a safe local filename for a resource URL.
    Uses an md5 hash of the full URL so any two distinct URLs never collide
    and the same URL always maps to the same file (stable across re-crawls).
    """
    digest = hashlib.md5(url.encode("utf-8")).hexdigest()[:16]

    ext = os.path.splitext(urlparse(url).path)[1].lower()
    # Extensions must be short/sane; anything else is guessed from content-type.
    if not re.fullmatch(r"\.[a-z0-9]{1,5}", ext or ""):
        ext = mimetypes.guess_extension((content_type or "").split(";")[0].strip()) or ""
        if ext == ".jpe":
            ext = ".jpg"

    return f"{digest}{ext}"


# ---------------------------------------------------------------------------
# JSON sidecar files: meta.json + resource_map.json
# ---------------------------------------------------------------------------

def write_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


def read_json(path: Path) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def build_meta(url: str, title: str, capture_date: str, timestamp: str, resource_count: int) -> dict:
    """Schema for meta.json -- kept intentionally small and stable."""
    return {
        "url": url,
        "title": title,
        "site_name": sanitize_site_name(url),
        "capture_date": capture_date,
        "capture_timestamp": timestamp,
        "resource_count": resource_count,
    }